# Generated by Django 4.1.7 on 2024-02-08 14:02

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rated', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('released', models.DateField(blank=True, default=None, null=True)),
                ('runtime', models.IntegerField(blank=True, default=None, null=True)),
                ('plot', models.TextField(blank=True, default='', null=True)),
                ('poster', models.URLField(blank=True, default=None, null=True)),
                ('imdbrating', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('imdbvotes', models.IntegerField(blank=True, default=None, null=True)),
                ('imdbid', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('boxoffice', models.IntegerField(blank=True, default=None, null=True)),
                ('actors', models.ManyToManyField(default=None, related_name='acted_movies', to='movies.person')),
                ('directors', models.ManyToManyField(default=None, related_name='directed_movies', to='movies.person')),
                ('writers', models.ManyToManyField(default=None, related_name='written_movies', to='movies.person')),
            ],
        ),
    ]
